"""Add is_trend, keywords, and trending_percentage to products

Revision ID: 0c717ce72ac6
Revises: 93db2199ce19
Create Date: 2025-06-01 08:08:37.640473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c717ce72ac6'
down_revision: Union[str, None] = '93db2199ce19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_trend', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('keywords', sa.String(), nullable=True))
    op.add_column('products', sa.Column('trending_percentage', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'trending_percentage')
    op.drop_column('products', 'keywords')
    op.drop_column('products', 'is_trend')
    # ### end Alembic commands ###
